---
name: 'Import GPG'
description: 'GitHub Action to easily import a GPG key'

inputs:
  gpg_private_key:
    description: 'GPG private key exported as an ASCII armored version or its base64 encoding'
    required: true
  passphrase:
    description: 'Passphrase of the GPG private key'
    required: false
  trust_level:
    description: "Set key's trust level"
    required: false
  git_config_global:
    description: 'Set Git config global'
    default: 'false'
    required: false
  git_user_signingkey:
    description: 'Set GPG signing keyID for this Git repository'
    default: 'false'
    required: false
  git_commit_gpgsign:
    description: 'Sign all commits automatically'
    default: 'false'
    required: false
  git_tag_gpgsign:
    description: 'Sign all tags automatically'
    default: 'false'
    required: false
  git_push_gpgsign:
    description: 'Sign all pushes automatically'
    default: 'if-asked'
    required: false
  git_committer_name:
    description: 'Commit author''s name'
    required: false
  git_committer_email:
    description: 'Commit author''s email'
    required: false
  workdir:
    description: 'Working directory (below repository root)'
    default: '.'
    required: false
  fingerprint:
    description: 'Specific fingerprint to use (subkey)'
    required: false

outputs:
  fingerprint:
    description: 'Fingerprint of the GPG key (recommended as user ID)'
    value: ${{ steps.setup-gpg.outputs.fingerprint }}
  keyid:
    description: 'Low 64 bits of the X.509 certificate SHA-1 fingerprint'
    value: ${{ steps.setup-gpg.outputs.keyid }}
  name:
    description: 'Name associated with the GPG key'
    value: ${{ steps.setup-gpg.outputs.name }}
  email:
    description: 'Email address associated with the GPG key'
    value: ${{ steps.setup-gpg.outputs.email }}

runs:
  using: "composite"
  steps:
    - name: setup-gpg
      id: setup-gpg
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ inputs.gpg_private_key }}
        passphrase: ${{ inputs.passphrase }}
        trust_level: ${{ inputs.trust_level }}
        git_config_global: ${{ inputs.git_config_global }}
        git_user_signingkey: ${{ inputs.git_user_signingkey }}
        git_commit_gpgsign: ${{ inputs.git_commit_gpgsign }}
        git_tag_gpgsign: ${{ inputs.git_tag_gpgsign }}
        git_push_gpgsign: ${{ inputs.git_push_gpgsign }}
        git_committer_name: ${{ inputs.git_committer_name }}
        git_committer_email: ${{ inputs.git_committer_email }}
        workdir: ${{ inputs.workdir }}
        fingerprint: ${{ inputs.fingerprint }}
