# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 1
    directory: "/checkout"
    schedule:
      interval: "daily"
    groups:
      updates:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 1
    directory: "/codecov"
    schedule:
      interval: "daily"
    groups:
      updates:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 1
    directory: "/codeql"
    schedule:
      interval: "daily"
    groups:
      updates:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 1
    directory: "/docker-build-and-push"
    schedule:
      interval: "daily"
    groups:
      updates:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 1
    directory: "/find-go-versions"
    schedule:
      interval: "daily"
    groups:
      updates:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 1
    directory: "/gherkin-lint"
    schedule:
      interval: "daily"
    groups:
      updates:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 1
    directory: "/git-add-and-commit"
    schedule:
      interval: "daily"
    groups:
      updates:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 1
    directory: "/github-get-release"
    schedule:
      interval: "daily"
    groups:
      updates:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 1
    directory: "/github-release"
    schedule:
      interval: "daily"
    groups:
      updates:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 1
    directory: "/golangci-lint"
    schedule:
      interval: "daily"
    groups:
      updates:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 1
    directory: "/import-gpg"
    schedule:
      interval: "daily"
    groups:
      updates:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 1
    directory: "/notify-go-registries"
    schedule:
      interval: "daily"
    groups:
      updates:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 1
    directory: "/notify-go-registry"
    schedule:
      interval: "daily"
    groups:
      updates:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 1
    directory: "/setup-go"
    schedule:
      interval: "daily"
    groups:
      updates:
        update-types:
          - "minor"
          - "patch"
