---
name: 'Build and push Docker Images'
description: 'Build and push Docker images to a Docker registry'

inputs:
  # Login
  registry:
    description: 'Server address of Docker registry. If not set then will default to Docker Hub'
    required: false
  username:
    description: 'Username used to log against the Docker registry'
    required: false
  password:
    description: 'Password or personal access token used to log against the Docker registry'
    required: false
  # Build and push
  build-args:
    description: "List of build-time variables"
    required: false
  context:
    description: "Build's context is the set of files located in the specified PATH or URL"
    required: false
  file:
    description: "Path to the Dockerfile"
    required: false
  push:
    description: "Push is a shorthand for --output=type=registry"
    required: false
    default: 'false'
  tags:
    description: "List of tags"
    required: false

outputs: {}

runs:
  using: "composite"
  steps:
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        build-args: ${{ inputs.build-args }}
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        push: ${{ inputs.push }}
        tags: ${{ inputs.tags }}

