---
name: 'Get the upload URL for a release'
description: 'Get the upload URL for a release for a tag in your repository'

inputs:
  token:
    description: "Authorized secret GitHub Personal Access Token. Defaults to github.token"
    required: false
    default: ${{ github.token }}

outputs:
  id:
    description: 'The ID of the release'
    value: ${{ steps.get-release.outputs.id }}
  html_url:
    description: 'The URL users can navigate to in order to view the release'
    value: ${{ steps.get-release.outputs.html_url }}
  upload_url:
    description: 'The URL for uploading assets to the release'
    value: ${{ steps.get-release.outputs.upload_url }}
  tag_name:
    description: 'The git tag associated with the release.'
    value: ${{ steps.get-release.outputs.tag_name }}
  name:
    description: 'The name of the release'
    value: ${{ steps.get-release.outputs.name }}
  body:
    description: 'The body of the release'
    value: ${{ steps.get-release.outputs.body }}
  draft:
    description: 'Whether this release is marked as a draft or not'
    value: ${{ steps.get-release.outputs.draft }}
  prerelease:
    description: 'Whether this release is marked as a pre-release or not'
    value: ${{ steps.get-release.outputs.prerelease }}

runs:
  using: "composite"
  steps:
    - name: Get release
      id: get-release
      uses: bruceadams/get-release@v1.3.2
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
