---
name: 'Codecov'
description: 'GitHub Action that uploads coverage reports for your repository to codecov.io'

inputs:
  token:
    description: 'Repository upload token - get it from codecov.io. Required only for private repositories'
    required: false
  file:
    description: 'Path to coverage file to upload'
    required: false
  files:
    description: 'Comma-separated list of files to upload'
    required: false
  directory:
    description: 'Directory to search for coverage reports.'
    required: false
  flags:
    description: 'Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)'
    required: false
  verbose:
    description: 'Specify whether the Codecov output should be verbose'
    required: false
  version:
    description: 'Specify which version of the Codecov CLI should be used. Defaults to `latest`'
    required: false
  slug:
    description: 'Specify the slug manually (Enterprise use)'
    required: false
  root-dir:
    description: 'Used when not in git/hg project to identify project root directory'
    required: false
    default: ${{ github.workspace }}
  working-directory:
    description: 'Directory in which to execute codecov.sh'
    required: false
    default: ${{ github.workspace }}

outputs: {}

runs:
  using: "composite"
  steps:
    - uses: codecov/codecov-action@v5
      with:
        token: ${{ inputs.token }}
        file: ${{ inputs.file }}
        files: ${{ inputs.files }}
        directory: ${{ inputs.directory }}
        flags: ${{ inputs.flags }}
        verbose: ${{ inputs.verbose }}
        version: ${{ inputs.version }}
        slug: ${{ inputs.slug }}
        root_dir: ${{ inputs.root-dir }}
        working-directory: ${{ inputs.working-directory }}

