---
name: "GitHub Release"
description: "Github Action for creating Github Releases"

inputs:
  body:
    description: "Note-worthy description of changes in release"
    required: false
  body_path:
    description: "Path to load note-worthy description of changes in release from"
    required: false
  name:
    description: "Gives the release a custom name. Defaults to tag name"
    required: false
  tag_name:
    description: "Gives a tag name. Defaults to github.GITHUB_REF"
    required: false
  draft:
    description: "Creates a draft release. Defaults to false"
    required: false
  prerelease:
    description: "Identify the release as a prerelease. Defaults to false"
    required: false
  files:
    description: "Newline-delimited list of path globs for asset files to upload"
    required: false
  fail_on_unmatched_files:
    description: "Fails if any of the `files` globs match nothing. Defaults to false"
    required: false
  repository:
    description: "Repository to make releases against, in <owner>/<repo> format"
    required: false
  token:
    description: "Authorized secret GitHub Personal Access Token. Defaults to github.token"
    required: false
    default: ${{ github.token }}
  target_commitish:
    description: "Commitish value that determines where the Git tag is created from. Can be any branch or commit SHA."
    required: false
  discussion_category_name:
    description: "If specified, a discussion of the specified category is created and linked to the release. The value must be a category that already exists in the repository. If there is already a discussion linked to the release, this parameter is ignored."
    required: false
  generate_release_notes:
    description: "Whether to automatically generate the name and body for this release. If name is specified, the specified name will be used; otherwise, a name will be automatically generated. If body is specified, the body will be pre-pended to the automatically generated notes."
    required: false
  append_body:
    description: "Append to existing body instead of overwriting it. Default is false."
    required: false

outputs:
  url:
    description: "URL to the Release HTML Page"
    value: ${{ steps.release.outputs.url }}
  id:
    description: "Release ID"
    value: ${{ steps.release.outputs.id }}
  upload_url:
    description: "URL for uploading assets to the release"
    value: ${{ steps.release.outputs.upload_url }}
  assets:
    description: "JSON array containing information about each uploaded asset, in the format given [here](https://docs.github.com/en/rest/reference/repos#upload-a-release-asset--code-samples) (minus the `uploader` field)"
    value: ${{ steps.release.outputs.assets }}

runs:
  using: "composite"
  steps:
    - id: release
      uses: softprops/action-gh-release@v1
      with:
        body: ${{ inputs.body }}
        body_path: ${{ inputs.body_path }}
        name: ${{ inputs.name }}
        tag_name: ${{ inputs.tag_name }}
        draft: ${{ inputs.draft }}
        prerelease: ${{ inputs.prerelease }}
        files: ${{ inputs.files }}
        fail_on_unmatched_files: ${{ inputs.fail_on_unmatched_files }}
        repository: ${{ inputs.repository }}
        token: ${{ inputs.token }}
        target_commitish: ${{ inputs.target_commitish }}
        discussion_category_name: ${{ inputs.discussion_category_name }}
        generate_release_notes: ${{ inputs.generate_release_notes }}
        append_body: ${{ inputs.append_body }}
